// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: 48aa3f1ea10551140445dee681c5236910dcd24b5f3f3b28bae92d16fac87553

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "DSFR";

export const themeNames: ThemeName[] = ["DSFR"];

export type KcEnvName =
    | "DSFR_THEME_HOME_URL"
    | "DSFR_THEME_SERVICE_TITLE"
    | "DSFR_THEME_BRAND_TOP"
    | "DSFR_NOTICE_TITLE"
    | "DSFR_NOTICE_DESCRIPTION"
    | "DSFR_NOTICE_SEVERITY"
    | "HUBEE_DOMAIN";

export const kcEnvNames: KcEnvName[] = [
    "DSFR_THEME_HOME_URL",
    "DSFR_THEME_SERVICE_TITLE",
    "DSFR_THEME_BRAND_TOP",
    "DSFR_NOTICE_TITLE",
    "DSFR_NOTICE_DESCRIPTION",
    "DSFR_NOTICE_SEVERITY",
    "HUBEE_DOMAIN"
];

export const kcEnvDefaults: Record<KcEnvName, string> = {
    DSFR_THEME_HOME_URL: "",
    DSFR_THEME_SERVICE_TITLE: "",
    DSFR_THEME_BRAND_TOP: "République<br/>Française",
    DSFR_NOTICE_TITLE: "",
    DSFR_NOTICE_DESCRIPTION: "",
    DSFR_NOTICE_SEVERITY: "info",
    HUBEE_DOMAIN: "basrec.hubee.numerique.gouv.fr"
};

/**
 * NOTE: Do not import this type except maybe in your entrypoint.
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext =
    | import("./login/KcContext").KcContext
    | import("./account/KcContext").KcContext;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));
export const KcAccountPage = lazy(() => import("./account/KcPage"));

export function KcPage(props: { kcContext: KcContext; fallback?: ReactNode }) {
    const { kcContext, fallback } = props;
    return (
        <Suspense fallback={fallback}>
            {(() => {
                switch (kcContext.themeType) {
                    case "login":
                        return <KcLoginPage kcContext={kcContext} />;
                    case "account":
                        return <KcAccountPage kcContext={kcContext} />;
                }
            })()}
        </Suspense>
    );
}

// NOTE: This is exported here only because in Webpack environnement it works differently
export const BASE_URL = import.meta.env.BASE_URL;

// NOTE: This is only exported here because you're supposed to import type from different packages
// Depending of if you are using Vite, Webpack, ect...
export type { Meta, StoryObj } from "@storybook/react-vite";
